//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanySector
    {
        public int companyID { get; set; }
        public short sectorID { get; set; }
        public int csID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Sector Sector { get; set; }
    }
}
