//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareTag
    {
        public int softwareID { get; set; }
        public short tagID { get; set; }
        public int stID { get; set; }
    
        public virtual Software Software { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
