//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Software()
        {
            this.Comments = new HashSet<Comment>();
            this.FavoriteSoftwares = new HashSet<FavoriteSoftware>();
            this.MonthlySoftwareStatistics = new HashSet<MonthlySoftwareStatistic>();
            this.SoftwareEdits = new HashSet<SoftwareEdit>();
            this.SoftwareIsFrees = new HashSet<SoftwareIsFree>();
            this.SoftwareNewPatches = new HashSet<SoftwareNewPatch>();
            this.SoftwareNotificationBlocks = new HashSet<SoftwareNotificationBlock>();
            this.SoftwareOldPatches = new HashSet<SoftwareOldPatch>();
            this.SoftwareStatistics = new HashSet<SoftwareStatistic>();
            this.SoftwareTags = new HashSet<SoftwareTag>();
            this.SoftwareVideos = new HashSet<SoftwareVideo>();
            this.SoftwareWorkPlatforms = new HashSet<SoftwareWorkPlatform>();
        }
    
        public int accountID { get; set; }
        public int softwareID { get; set; }
        public string softwareName { get; set; }
        public string description { get; set; }
        public string softwareVersion { get; set; }
        public byte[] softwareImg { get; set; }
        public System.DateTime softwareCreatedDate { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteSoftware> FavoriteSoftwares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlySoftwareStatistic> MonthlySoftwareStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareEdit> SoftwareEdits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareIsFree> SoftwareIsFrees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareNewPatch> SoftwareNewPatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareNotificationBlock> SoftwareNotificationBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareOldPatch> SoftwareOldPatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareStatistic> SoftwareStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareTag> SoftwareTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareVideo> SoftwareVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareWorkPlatform> SoftwareWorkPlatforms { get; set; }
    }
}
