//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareVideo
    {
        public int softwareID { get; set; }
        public string softwareVideoLink { get; set; }
        public int svID { get; set; }
    
        public virtual Software Software { get; set; }
    }
}
