//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareWorkPlatform
    {
        public int softwareID { get; set; }
        public Nullable<bool> isWindows { get; set; }
        public Nullable<bool> isLinux { get; set; }
        public Nullable<bool> isUnix { get; set; }
        public Nullable<bool> isPardus { get; set; }
        public Nullable<bool> isAndroid { get; set; }
        public Nullable<bool> isIOS { get; set; }
        public Nullable<bool> isDesktopApp { get; set; }
        public Nullable<bool> isWebApp { get; set; }
        public Nullable<bool> isOthers { get; set; }
        public int swpID { get; set; }
        public Nullable<bool> isMacOS { get; set; }
    
        public virtual Software Software { get; set; }
    }
}
