//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftwareIsFree
    {
        public int softwareID { get; set; }
        public Nullable<bool> isDemo { get; set; }
        public Nullable<bool> isFullVersion { get; set; }
        public Nullable<bool> isBeta { get; set; }
        public Nullable<bool> isFree { get; set; }
        public int sifID { get; set; }
    
        public virtual Software Software { get; set; }
    }
}
