//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Station
    {
        public int companyID { get; set; }
        public string stationName { get; set; }
        public string stationAddress { get; set; }
        public string stationTelNum { get; set; }
        public string stationDescription { get; set; }
        public int sID { get; set; }
        public string stationWebSite { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
