//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDSI_TurkiyeYerliYazilimEnvanteri.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ticketID { get; set; }
        public int accountID { get; set; }
        public short ticketTypeID { get; set; }
        public string ticketContent { get; set; }
        public int complainedID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TicketTitle TicketTitle { get; set; }
    }
}
